/control/verbose 2
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/detector/setParaffinX 12 cm
/detector/setParaffinY 15 cm
/detector/setParaffinZ 4.5 cm
/detector/setLeadZ 1.5 cm

/run/initialize

# Visualización
/vis/open OGL
/vis/viewer/set/viewpointThetaPhi 90 0
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/enable
/vis/viewer/refresh

# Configuración del haz
/gun/particle neutron
/gun/energy 4.2 MeV
/gun/position 0 0 -4.6 cm
/gun/direction 0 0 1
/gun/number 1

# Simulación
/run/beamOn 5


