/control/verbose 2
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/detector/setParaffinX 12 cm
/detector/setParaffinY 15 cm
/detector/setParaffinZ 4.5 cm

/run/initialize

# Visualización
/vis/open OGL 2000x2000
/vis/viewer/set/viewpointThetaPhi 30 20




/vis/geometry/set/colour Block 0 226 212 183 .3
/vis/geometry/set/colour Detector 0 28 28 28 1
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate


# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.5 -.9 24 ! ! Phase 1 : Thermalization
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)

/vis/scene/add/axes -12 -15 -4.5 30 cm

/vis/enable
/vis/viewer/refresh

# Configuración del haz
/gun/particle neutron
/gun/energy 4.2 MeV
/gun/position 0 0 -4.6 cm
/gun/direction 0 0 1
/gun/number 1

# Simulación
/run/beamOn 1



