/control/verbose 2
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/detector/setParaffinX 6 cm
/detector/setParaffinY 6 cm
/detector/setParaffinZ 4 cm
/detector/setLeadZ 2 cm

/run/initialize

# Visualización
/vis/open OGL 2000x2000
/vis/viewer/set/viewpointThetaPhi 30 20




/vis/geometry/set/colour Block 0 226 212 183 .3
/vis/geometry/set/colour Detector 0 28 28 28 1
/vis/geometry/set/colour Lead 0 0 212 200 .3
/vis/viewer/set/style surface
/vis/viewer/set/autoRefresh true
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate


# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.5 -.9 24 ! ! Phase 1 : Thermalization
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)

/vis/scene/add/axes -12 -15 -4.5 30 cm

/vis/enable
/vis/viewer/refresh

# Simulación
/run/beamOn 1



