# vis_video_geo4.mac — Placa cuadrada: 20x20x8 cm
/control/macroPath ../macros
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Geometría (half-lengths)
/detector/setParaffinX 10 cm
/detector/setParaffinY 10 cm
/detector/setParaffinZ 4 cm
/detector/setLeadZ 1.5 cm

# Fuente AmBe
/ambe/distance 3 cm
/ambe/activity 2.98

/run/initialize

# Visualización
/vis/open OGLSX 1280x720
/vis/viewer/set/viewpointThetaPhi 70 20
/vis/viewer/set/background 0 0 0 1
/vis/geometry/set/colour Block    0 1.0 1.0 0.6 0.6
/vis/geometry/set/colour Lead     0 0.6 0.6 0.6 0.8
/vis/geometry/set/colour Detector 0 1.0 0.55 0.0 1.0
/vis/viewer/set/style wireframe
/vis/geometry/set/forceSolid Detector 0
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/scene/endOfRunAction accumulate

# Colores por tipo de partícula
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron white
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- red

# Etiqueta
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -0.9 18 ! ! Square Plate  20x20x8 cm
/vis/set/textLayout
/vis/set/textColour
/vis/scene/add/axes -10 -10 -7 10 cm

/vis/enable
/vis/viewer/refresh
/vis/ogl/set/exportFormat eps

# 120 eventos, 1 por frame
/control/loop vis_video_frame.mac i 1 120 1
