# vis_video.mac — 120 eventos, acumulación partícula a partícula
/control/macroPath ../macros
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Geometría
/detector/setParaffinX 6 cm
/detector/setParaffinY 6 cm
/detector/setParaffinZ 4 cm
/detector/setLeadZ 2 cm

# Fuente AmBe
/ambe/distance 0 cm
/ambe/activity 2.98

/run/initialize

# Visualización
/vis/open OGLSX 2000x2000
/vis/viewer/set/viewpointThetaPhi 30 20
/vis/geometry/set/colour Block 0 226 212 183 .3
/vis/geometry/set/colour Detector 0 28 28 28 1
/vis/geometry/set/colour Lead 0 0 212 200 .3
/vis/viewer/set/style wireframe
/vis/geometry/set/forceSolid Detector 0
/vis/scene/create
/vis/scene/add/volume
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate
/vis/scene/endOfRunAction accumulate

# Colores por tipo de partícula
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set e- red

# Etiqueta
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -0.9 18 ! ! AmBe Neutron Thermalization
/vis/set/textLayout
/vis/set/textColour
/vis/scene/add/axes -10 -10 -13 10 cm

/vis/enable
/vis/viewer/refresh
/vis/ogl/set/exportFormat eps

# 120 eventos, 1 por frame — 60 fps → 2 segundos
/control/loop vis_video_frame.mac i 1 120 1
